[tools]
rust = "nightly-2024-09-23"
node = "latest"
deno = "latest"
erlang = "27.0"
elixir = "latest"
gleam = "1.2.1"
rebar = "latest"
python = "latest"
bun = "1.1.29"
go = "latest"
just = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
